[package]
name = "containerflare-basic-example"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
axum = "0.7"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
containerflare = { path = "../..", version = "0.1.0" }
