[package]
name = "containerflare-basic-example"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
axum = "0.7"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
containerflare = { path = "../..", version = "0.1.0" }
